# Generated by Django 5.1.4 on 2025-01-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_booking_user_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(choices=[('owner', 'owner'), ('client', 'client')], default='client', max_length=16),
        ),
    ]
